# Site settings
title: iloveulhj.github.io
email: iloveulhj@gmail.com
description: 
 이 블로그는 Web 개발에 관련된 주제를 다룹니다.
 Java, HTTP, linux, python...
copyright:
 Copyright © <span class="footer-heading-owner">HoJung</span>. All rights reserved.
 Powered by <a href="http://jekyllrb.com">Jekyll</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iloveulhj.github.io"
github_username:  iloveulhj

# URL setting
permalink: none

# Build settings
markdown: kramdown


